apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service
  labels:
    app: content-service
    keel.sh/policy: force
    keel.sh/trigger: poll
  annotations:
      keel.sh/pollSchedule: "@every 1m"
      keel.sh/policy: 'major'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: content-service
  template:
    metadata:
      labels:
        app: content-service
    spec:
      containers:
      - name: content-service
        image: aimvector/marcel-dev:0.0.5-uicontentservice
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: myregistrykey
---
kind: Service
apiVersion: v1
metadata:
  name: content-service
spec:
  selector:
    app: content-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80