apiVersion: apps/v1
kind: Deployment
metadata:
  name: footer-service
  labels:
    app: footer-service
    keel.sh/policy: force
    keel.sh/trigger: poll
  annotations:
      keel.sh/pollSchedule: "@every 1m"
      keel.sh/policy: major"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: footer-service
  template:
    metadata:
      labels:
        app: footer-service
    spec:
      containers:
      - name: footer-service
        image: aimvector/marcel-dev:0.0.8-uifooterservice
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /status
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: footer-service
spec:
  selector:
    app: footer-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80