apiVersion: apps/v1
kind: Deployment
metadata:
  name: footer-service
  labels:
    app: footer-service
    keel.sh/policy: all
    keel.sh/trigger: poll
  annotations:
      keel.sh/pollSchedule: "@every 10s"
      keel.sh/policy: "glob:ui-footer-microservice*"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: footer-service
  template:
    metadata:
      labels:
        app: footer-service
    spec:
      containers:
      - name: footer-service
        image: aimvector/marcel-dev:ui-footer-microservice-0.0.4
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: footer-service
spec:
  selector:
    app: footer-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80