apiVersion: apps/v1
kind: Deployment
metadata:
  name: header-service
  labels:
    app: header-service
    keel.sh/policy: force
    keel.sh/trigger: poll
  annotations:
      keel.sh/pollSchedule: "@every 1m"
      keel.sh/policy: "major"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: header-service
  template:
    metadata:
      labels:
        app: header-service
    spec:
      containers:
      - name: header-service
        image: aimvector/marcel-dev:0.0.7-uiheaderservice
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /status
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
---
kind: Service
apiVersion: v1
metadata:
  name: header-service
spec:
  selector:
    app: header-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80